version: "3.8"

services:
  db:
    image: postgres:15
    container_name: highdemand
    environment:
      POSTGRES_DB: highdemand
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: high-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
