spring.application.name=highdemand


spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.url=jdbc:postgresql://db:5432/highdemand
spring.jpa.hibernate.ddl-auto=update
