spring.application.name=highdemand


spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/highdemand
spring.datasource.username=postgres
spring.datasource.password=35482093
spring.jpa.hibernate.ddl-auto=update